DAGH_run2_194 *10 poly
python: can't open file 'DAGH_run_194.py': [Errno 2] No such file or directory
###################################
0, 0, 0
###################################
python: can't open file 'DAGH_run_194.py': [Errno 2] No such file or directory
###################################
0, 0.01, 0
###################################
python: can't open file 'DAGH_run_194.py': [Errno 2] No such file or directory
###################################
0, 0.02, 0
###################################
python: can't open file 'DAGH_run_194.py': [Errno 2] No such file or directory
###################################
0, 0.03, 0
###################################
python: can't open file 'DAGH_run_194.py': [Errno 2] No such file or directory
###################################
0, 0.04, 0
###################################
python: can't open file 'DAGH_run_194.py': [Errno 2] No such file or directory
###################################
0.01, 0, 0
###################################
python: can't open file 'DAGH_run_194.py': [Errno 2] No such file or directory
###################################
0.01, 0.01, 0
###################################
python: can't open file 'DAGH_run_194.py': [Errno 2] No such file or directory
###################################
0.01, 0.02, 0
###################################
python: can't open file 'DAGH_run_194.py': [Errno 2] No such file or directory
###################################
0.01, 0.03, 0
###################################
python: can't open file 'DAGH_run_194.py': [Errno 2] No such file or directory
###################################
0.01, 0.04, 0
###################################
python: can't open file 'DAGH_run_194.py': [Errno 2] No such file or directory
###################################
0.02, 0, 0
###################################
python: can't open file 'DAGH_run_194.py': [Errno 2] No such file or directory
###################################
0.02, 0.01, 0
###################################
python: can't open file 'DAGH_run_194.py': [Errno 2] No such file or directory
###################################
0.02, 0.02, 0
###################################
python: can't open file 'DAGH_run_194.py': [Errno 2] No such file or directory
###################################
0.02, 0.03, 0
###################################
python: can't open file 'DAGH_run_194.py': [Errno 2] No such file or directory
###################################
0.02, 0.04, 0
###################################
